// Code generated by RedSock CLI.
// DO EDIT, DON'T DELETE THIS FILE.

package app

import (
	"context"
	"database/sql"

	errors "github.com/Red-Sock/trace-errors"
	"github.com/pressly/goose/v3"
	"github.com/rs/zerolog/log"
	"github.com/soheilhy/cmux"
	"go.redsock.ru/rerrors"
	"go.redsock.ru/toolbox/closer"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	"github.com/godverv/hello_world/internal/transport"
	"github.com/godverv/hello_world/internal/transport/docs"
	impl "github.com/godverv/hello_world/internal/transport/grpc/api"
	hw "github.com/godverv/hello_world/pkg/hello_world"
)

type Custom struct {
	ServerManager *transport.ServersManager
}

func (c *Custom) Init(a *App) (err error) {
	db, err := pickDB(a)
	if err != nil {
		return rerrors.Wrap(err, "error picking database")
	}

	grpcImpl := impl.New(db, a.Cfg)

	peer, err := c.initPeer(a)
	if err != nil {
		return rerrors.Wrap(err, "error initializing peer")
	}

	grpcImpl.WithPeer(peer)

	c.ServerManager, err = transport.NewServerManager(a.Ctx, a.MASTER)
	if err != nil {
		return rerrors.Wrap(err, "error during initialization of a server manager")
	}

	c.ServerManager.AddImplementation(grpcImpl)

	c.ServerManager.AddHttpHandler(docs.Swagger())

	return nil
}

func (c *Custom) initPeer(a *App) (hw.HelloWorldAPIClient, error) {
	if a.Cfg.Environment.PeerGrpcURL == "" {
		return nil, nil
	}

	conn, err := grpc.NewClient(a.Cfg.Environment.PeerGrpcURL,
		grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return nil, rerrors.Wrap(err, "error connecting to peer")
	}

	closer.Add(conn.Close)
	log.Info().Str("peer", a.Cfg.Environment.PeerGrpcURL).Msg("peer service configured")
	return hw.NewHelloWorldAPIClient(conn), nil

}

func pickDB(a *App) (*sql.DB, error) {
	if a.Cfg.Environment.StatefullPgURL == "" {
		log.Info().Msg("stateless mode: using SQLite")
		return a.Sqlite, nil
	}

	log.Info().Msg("stateful mode: using PostgreSQL")
	db, err := sql.Open("postgres", a.Cfg.Environment.StatefullPgURL)
	if err != nil {
		return nil, rerrors.Wrap(err, "error opening postgres connection")
	}

	goose.SetLogger(gooseLogger{})

	err = goose.SetDialect("postgres")
	if err != nil {
		db.Close()
		return nil, rerrors.Wrap(err, "error setting goose dialect")
	}

	err = goose.Up(db, "./migrations")
	if err != nil {
		db.Close()
		return nil, rerrors.Wrap(err, "error running postgres migrations")
	}

	closer.Add(db.Close)
	return db, nil
}

type gooseLogger struct{}

func (g gooseLogger) Fatalf(format string, v ...interface{}) { log.Fatal().Msgf(format, v...) }
func (g gooseLogger) Printf(format string, v ...interface{}) { log.Info().Msgf(format, v...) }

func (c *Custom) Start(_ context.Context) error {
	err := c.ServerManager.Start()
	if err != nil && !errors.Is(err, cmux.ErrServerClosed) {
		return rerrors.Wrap(err, "error starting server manager")
	}

	return nil
}

func (c *Custom) Stop() error {
	err := c.ServerManager.Start()
	if err != nil {
		return rerrors.Wrap(err, "error stopping server manager")
	}

	return nil
}
